kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: docker_repo
    registry:
      from_secret: docker_registry
    dockerfile: webpage/my-app/Dockerfile

trigger:
  event:
  - promote
  target:
  - production