kind: pipeline
type: kubernetes
name: fancy-mumble

steps:
- name: build_dev_frontend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    registry: docker.magical.rocks
    cache_from: docker.magical.rocks/dev-fancy-mumble:latest
    repo: docker.magical.rocks/dev-fancy-mumble
    dockerfile: webpage/my-app/Dev.Dockerfile
- name: publish_frontend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    cache_from:
      from_secret: docker_full_project_name
    registry:
      from_secret: docker_registry
    repo:
      from_secret: docker_repo
    dockerfile: webpage/my-app/Dockerfile
- name: publish_backend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    cache_from:
      from_secret: docker_full_project_name_backend
    registry:
      from_secret: docker_registry
    repo:
      from_secret: docker_repo_backend
    dockerfile: brocker/Dockerfile