kind: pipeline
type: kubernetes
name: fancy-mumble

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - 0.0.1
    registry:
      from_secret: docker_registry
    repo:
      from_secret: docker_repo
    dockerfile: webpage/my-app/Dockerfile