kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: fancy-mumble
    tags: latest
    registry:
      from_secret: docker_registry
    dockerfile: webpage/my-app/Dockerfile